apiVersion: v1
kind: ConfigMap
metadata:
  name: genomic-data
data:
  genomic_data: |
    [
      {
        "VarietyID": "11430",
        "AccessionID": "11430_H",
        "AccessionHolding": "inra",
        "MaterialSourceDOI": "https://doi.org/10.15454/MDSCXQ",
        "MaterialSourceID": "inra:11430_H",
        "BiologicalMaterialID": "11430_H",
        "Organism": "NCBITAXON:4577",
        "Genus": "Zea",
        "Species": "mays",
        "InfraspecificName": "11430",
        "Parent1": "11430_usda",
        "Parent1Synonym": "11430_usda",
        "Parent1Holding": "USDA",
        "Parent2": "UH_007",
        "Parent2Holding": "UH",
        "CodeID": "3101",
        "Panel246": "yes",
        "GeneticGroup": "Iodent",
        "Holding": "CIAM, Spain",
        "HoldingName": "Centro de Investigaciones Agrarias de Mabegondo"
      }
    ]