apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-sender
  template:
    metadata:
      labels:
        app: plant-sender
    spec:
      containers:
      - name: plant-sender
        image: plant-sender:latest
        imagePullPolicy: Never
        env:
          - name: PLANT_NAME
            value: "plant1"
          - name: GENE_VARIETY
            value: "11430"
          - name: RECEIVER_URL
            value: "http://receiver-service:5000/receive_data"
          - name: SEND_INTERVAL
            value: "10"
        volumeMounts:
          - name: actual-images
            mountPath: /app/data  # Keep only this mount
      volumes:
        - name: actual-images
          hostPath:
            path: /data  # This is mounted from kind cluster
            type: Directory
