apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-setup
data:
  setup.sh: |
    #!/bin/sh
    until mongosh mongodb-service:27017 --eval "print('waited for connection')"; do
      sleep 2
    done
    
    mongosh mongodb-service:27017 --eval '
      db = db.getSiblingDB("admin");
      db.createUser({
        user: "root",
        pwd: "example",
        roles: [{ role: "root", db: "admin" }]
      });
      
      db = db.getSiblingDB("plant_data");
      db.createUser({
        user: "plant_user",
        pwd: "plant_pass",
        roles: [{ role: "readWrite", db: "plant_data" }]
      });
    ' 